import { z } from "zod";

// Schemas
export const SearchCodeSchema = z.object({ 
  query: z.string().min(1, "Query is required"),
  sessionId: z.string().optional()
});

export const GenerateSuggestionSchema = z.object({
  query: z.string().min(1, "Query is required").optional(),
  prompt: z.string().min(1, "Prompt is required").optional(),
  sessionId: z.string().optional()
}).transform((data) => ({
  query: data.query || data.prompt || "",
  sessionId: data.sessionId
})).refine(data => data.query.length > 0, {
  message: "Either query or prompt must be a non-empty string",
  path: ["query"],
});

export const GetRepositoryContextSchema = z.object({ 
  query: z.string().min(1, "Query is required"),
  sessionId: z.string().optional()
}).or(
  z.string().min(1, "Query is required").transform(query => ({ query }))
);

export const FeedbackSchema = z.object({
  sessionId: z.string().optional(),
  feedbackId: z.string().optional(),
  score: z.number().min(1).max(10),
  comments: z.string(),
  originalQuery: z.string(),
  suggestion: z.string()
});

// Agent schema
export const AgentQuerySchema = z.object({
  query: z.string().min(1, "Query is required"),
  sessionId: z.string().optional(),
  maxSteps: z.number().optional().default(5)
});

// Types
export interface OllamaEmbeddingResponse { 
  embedding: number[] 
}

export interface OllamaGenerateResponse { 
  response: string 
}

export interface QdrantPoint { 
  id: string; 
  vector: number[]; 
  payload: { 
    filepath: string; 
    content: string; 
    last_modified: string 
  } 
}

export interface QdrantSearchResult { 
  id: string | number; 
  payload: { 
    content: string; 
    filepath: string; 
    last_modified: string 
  }; 
  score: number 
}

// Agent types
export interface AgentStep {
  tool: string;
  input: unknown;
  output: unknown;
  reasoning: string;
}

export interface AgentState {
  sessionId: string;
  query: string;
  planText?: string; // Stores the raw plan generated by the LLM
  steps: AgentStep[]; // Stores executed steps or a structured plan
  context: unknown[];
  finalResponse?: string;
  isComplete: boolean;
}

export interface AgentInitialQueryResponse {
  sessionId: string;
  status: "PLAN_GENERATED" | "ERROR"; // Initial statuses
  message: string;
  generatedPlanText?: string; // The raw plan text from the LLM
  agentState: AgentState; // The complete, updated agent state including the planText
}

export interface DetailedQdrantSearchResult {
  id: string | number;
  score: number;
  payload: {
    filepath: string;
    content: string;
    last_modified: string;
    [key: string]: unknown; // Allows for other potential payload fields
  };
  version?: number;
  vector?: number[] | Record<string, unknown> | number[][] | null;
  shard_key?: string;
  order_value?: number;
}
